// Code generated by reset generator. DO NOT EDIT.

package simple

func (u *User) Reset() {
	if u == nil {
		return
	}
	u.ID = 0
	u.Name = ""
	u.Score = 0
	u.Active = false
	u.Tags = u.Tags[:0]
	clear(u.Meta)
}
