// Code generated by reset generator. DO NOT EDIT.

package pointers

func (s *Session) Reset() {
	if s == nil {
		return
	}
	s.Token = ""
	if s.TokenPtr != nil {
		*s.TokenPtr = ""
	}
	if s.Count != nil {
		*s.Count = 0
	}
	if resetter, ok := any(s.Child).(interface{ Reset() }); ok && s.Child != nil {
		resetter.Reset()
	}
}
