package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

// Шаблон генерируемого файла.
const resetTemplate = `// Code generated by reset generator. DO NOT EDIT.

package {{.Package}}

{{range .Structs}}
func ({{.Receiver}} *{{.Name}}) Reset() {
	if {{.Receiver}} == nil {
		return
	}
{{range .Fields}}	{{.}}
{{end}}}
{{end}}`

var tmpl = template.Must(template.New("reset").Parse(resetTemplate))

func main() {
	pattern := "./..."
	if len(os.Args) > 1 {
		pattern = os.Args[1]
	}

	fset := token.NewFileSet()
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedSyntax | packages.NeedFiles,
		Fset: fset,
		ParseFile: func(fset *token.FileSet, filename string, src []byte) (*ast.File, error) {
			return parser.ParseFile(fset, filename, src, parser.ParseComments)
		},
	}

	pkgs, err := packages.Load(cfg, pattern)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error loading packages: %v\n", err)
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 || len(pkg.GoFiles) == 0 {
			continue
		}

		structs := findResetStructs(pkg.Syntax)
		if len(structs) == 0 {
			continue
		}

		dir := filepath.Dir(pkg.GoFiles[0])
		if err := writeGenFile(dir, pkg.Name, structs); err != nil {
			fmt.Fprintf(os.Stderr, "error writing %s: %v\n", dir, err)
			os.Exit(1)
		}

		fmt.Printf("generated reset.gen.go in %s (%d structs)\n", dir, len(structs))
	}
}

// StructInfo хранит данные об одной структуре для передачи в шаблон.
type StructInfo struct {
	Name     string
	Receiver string
	Fields   []string // готовые строки кода сброса
}

// templateData — данные, передаваемые в text/template.
type templateData struct {
	Package string
	Structs []StructInfo
}

// findResetStructs ищет структуры с комментарием // generate:reset.
func findResetStructs(files []*ast.File) []StructInfo {
	var result []StructInfo
	for _, file := range files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			// Комментарий над всем type(...) блоком распространяется на все структуры внутри.
			declTagged := hasGenerateReset(genDecl.Doc)

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				if !declTagged && !hasGenerateReset(typeSpec.Comment) {
					continue
				}
				st, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				result = append(result, buildStructInfo(typeSpec.Name.Name, st))
			}
		}
	}
	return result
}

// hasGenerateReset проверяет наличие маркера // generate:reset в комментарии.
func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		if c.Text == "// generate:reset" {
			return true
		}
	}
	return false
}

// buildStructInfo собирает информацию о структуре: ресивер и строки сброса полей.
func buildStructInfo(name string, st *ast.StructType) StructInfo {
	// Ресивер: первая буква имени в нижнем регистре.
	recv := strings.ToLower(string(name[0]))
	si := StructInfo{Name: name, Receiver: recv}

	for _, field := range st.Fields.List {
		// Embedded-поле (len == 0): по ТЗ вложенные структуры с Reset() должны его вызывать.
		if len(field.Names) == 0 {
			if code := embeddedResetCode(recv, field.Type); code != "" {
				si.Fields = append(si.Fields, code)
			}
			continue
		}
		for _, fn := range field.Names {
			if code := resetCode(recv, fn.Name, field.Type); code != "" {
				si.Fields = append(si.Fields, code)
			}
		}
	}
	return si
}

// embeddedResetCode генерирует вызов Reset() для embedded-поля, если тип его поддерживает.
func embeddedResetCode(recv string, typ ast.Expr) string {
	typeName := embeddedTypeName(typ)
	if typeName == "" {
		return ""
	}
	ref := recv + "." + typeName
	return fmt.Sprintf(
		`if resetter, ok := any(&%s).(interface{ Reset() }); ok { resetter.Reset() }`,
		ref,
	)
}

// embeddedTypeName извлекает имя встроенного типа для обращения к полю.
func embeddedTypeName(typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		// pkg.Type - обращаемся по короткому имени Type
		return t.Sel.Name
	case *ast.StarExpr:
		return embeddedTypeName(t.X)
	}
	return ""
}

// resetCode генерирует строку кода сброса для одного именованного поля.
func resetCode(recv, fieldName string, typ ast.Expr) string {
	ref := recv + "." + fieldName
	switch t := typ.(type) {
	case *ast.Ident:
		// Примитив -> нулевое значение.
		if zero := primitiveZero(t.Name); zero != "" {
			return ref + " = " + zero
		}
		// Именованный тип (структура) - вызываем Reset() через интерфейс с адресом,
		// чтобы найти метод с pointer-ресивером.
		return fmt.Sprintf(
			`if resetter, ok := any(&%s).(interface{ Reset() }); ok { resetter.Reset() }`,
			ref,
		)

	case *ast.ArrayType:
		if t.Len == nil {
			// Слайс обрезается к нулевой длине, но память не освобождается.
			return ref + " = " + ref + "[:0]"
		}
		// Фиксированные массивы пропускаем.
		return ""

	case *ast.MapType:
		return "clear(" + ref + ")"

	case *ast.StarExpr:
		return ptrResetCode(recv, fieldName, t.X)

	case *ast.SelectorExpr:
		// Тип из другого пакета (pkg.Type).
		return fmt.Sprintf(
			`if resetter, ok := any(&%s).(interface{ Reset() }); ok { resetter.Reset() }`,
			ref,
		)

	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return ref + " = nil"
	}
	return ""
}

// ptrResetCode генерирует сброс для полей-указателей.
// По ТЗ: все ненулевые указатели сбрасывают значения по правилам выше.
func ptrResetCode(recv, fieldName string, inner ast.Expr) string {
	ref := recv + "." + fieldName
	switch t := inner.(type) {
	case *ast.Ident:
		if zero := primitiveZero(t.Name); zero != "" {
			// *string, *int и т.д. — разыменовываем и присваиваем ноль.
			return fmt.Sprintf("if %s != nil { *%s = %s }", ref, ref, zero)
		}
		// *SomeStruct — вызываем Reset() напрямую (метод с pointer-ресивером).
		return fmt.Sprintf(
			`if resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil { resetter.Reset() }`,
			ref, ref,
		)

	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("if %s != nil { *%s = (*%s)[:0] }", ref, ref, ref)
		}
		return ""

	case *ast.MapType:
		return fmt.Sprintf("if %s != nil { clear(*%s) }", ref, ref)

	case *ast.SelectorExpr:
		return fmt.Sprintf(
			`if resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil { resetter.Reset() }`,
			ref, ref,
		)
	}
	return ""
}

// primitiveZero возвращает нулевое значение для встроенных примитивных типов Go.
func primitiveZero(name string) string {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return "0"
	case "string":
		return `""`
	case "bool":
		return "false"
	}
	return ""
}

// writeGenFile рендерит шаблон и записывает reset.gen.go в директорию пакета.
func writeGenFile(dir, pkgName string, structs []StructInfo) error {
	var buf bytes.Buffer

	data := templateData{
		Package: pkgName,
		Structs: structs,
	}
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("executing template: %w", err)
	}

	// Форматируем через go/format — как в примерах из курса.
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("formatting generated code: %w\nraw output:\n%s", err, buf.String())
	}

	outPath := filepath.Join(dir, "reset.gen.go")
	return os.WriteFile(outPath, src, 0644)
}
